config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.settings import DEBUG
import main.urls
import carts.urls
import users.urls
import orders.urls
import goods.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(main.urls, namespace="main")),
    # path("cart/", include(carts.urls), name = 'cart'),
    path("user/", include(users.urls, namespace="users")),
    # path("order/", include(orders.urls)),
    path("catalog/", include(goods.urls, namespace="goods")),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

goods/urls.py
from django.urls import path, include
from goods import views

app_name = "goods"
urlpatterns = [
    path("", views.category, name="category"),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path
from users import views
app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
]

carts/models.py
from django.db import models

# Create your models here.

goods/models/categories.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)
    slug = models.SlugField(
        max_length=200,
        unique=True,
        blank=True,
        null=True,
        verbose_name="URL",
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return f"{self.name} ({self.pk})"

goods/models/goods.py
from django.db import models


class Product(models.Model):

    name = models.CharField(max_length=150, unique=True)

    slug = models.SlugField(
        max_length=200,
        unique=True,
        blank=True,
        null=True,
        verbose_name="URL",
    )
    description = models.TextField()
    image = models.ImageField(upload_to="goods_images", blank=True, null=True)
    amount = models.PositiveIntegerField(default=0, null=True)
    Price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2)
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2)
    category = models.ForeignKey("Category", models.CASCADE)

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def __str__(self):
        return f"{self.name} ({self.pk})"

main/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

carts/views.py
from django.shortcuts import render

# Create your views here.

goods/views.py
from django.shortcuts import render
from goods.models.categories import Category
from goods.models.goods import Product


def category(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {"title": "Catalog", "categories": categories, "products": products}

    return render(request, "goods/goods.html", context)

main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'main/index.html')

orders/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render

def login(request):
    return render(request, 'users/login.html')
def registration(request):
    return render(request, 'users/registration.html')


def profile(request):
    return render(request, 'users/profile.html')

goods/templates/goods/goods.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/goods.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/navigation-goods.css" %}">
{% endblock %}

{% block js %}
    <script src="{% static "deps/js/navigations.js"%}" defer></script>
    <script src="{% static "deps/js/goods.js"%}" defer></script>
{% endblock %}

{% block sidenav %}
	{% for category in categories %}
				<button class="dropdown-btn"><b>&equiv; {{category.name}}</b></button>
				<div class="dropdown-container">
						{% for product in products %}
								{% if product.category == category %}
									<button><b>{{product.name}}</b></button>
								{% endif %}
						{% endfor %}
        </div>
	{% endfor %}

 {% endblock %}

goods/templates/goods/hoodie.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static "deps/css/hoddie.css"%}">
{% endblock %}



{% block main %}
 <div class="centered-text"><b>Худи</b></div>
{% endblock %}

goods/templates/goods/jeans.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
 <link rel="stylesheet" href="{% static "deps/css/jean.css"%}">
{% endblock %}



{% block main %}
<div class="centered-text"><b>Джинсы</b></div>
{% endblock %}

goods/templates/goods/sweatshirts.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
 <link rel="stylesheet" href="{% static "deps/css/sweatshirts.css"%}">
{% endblock %}



{% block main %}
<div class="centered-text"><b>Свитшоты</b></div>
{% endblock %}

goods/templates/goods/t-shirts.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static "deps/css/navigation-goods.css"%}">
<link rel="stylesheet" href="{% static "deps/css/t-shirts.css"%}">
{% endblock %}



{% block main %}
<div class="centered-text"><b>Футболки</b></div>
{% endblock %}

goods/templates/goods/trousers.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static "deps/css/trousers.css"%}">
{% endblock %}



{% block main %}
<div class="centered-text"><b>Штаны</b></div>
{% endblock %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}



{% block main %}
<div class="centered-text"><b>Fresh Style Shop</b></div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Sakura - утилита ВКонтакте для автоматизации действий.">
    <meta name="author" content="Inovatik">


	  <meta property="og:site_name" content="FreshStyle" />
	  <meta property="og:site" content="sakuraduty.ru" />
	  <meta property="og:title" content="Shop"/>
	  <meta property="og:description" content="Молодежная одежда по цене шаурмы :)" />
	  <meta property="og:image" content="" />
	  <meta property="og:url" content="https://vk.com/FreshStyleShop" />
    <meta property="og:type" content="article" />

    <link rel="stylesheet" href=" {% static "deps/css/index.css" %} ">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Balega&display=swap">
    {% block css %}

    {% endblock %}
    <link rel="stylesheet" href=" {% static "deps/images/background.jpg" %} ">
    <script src="{% static "deps/js/index.js" %}" defer></script>
    <script src="{% static "deps/js/carousel.js" %}" defer></script>
    {% block js %}

    {% endblock %}

    <title>{{ title }}</title>
</head>
<style>
body {
  background-image: url({% static "deps/images/background.jpg" %});
  background-size: cover; /* Растягивание изображения на весь фон */
  background-position: center; /* Центрируем изображение */
  background-attachment: fixed; /* Фиксируем изображение, чтобы оно оставалось на месте при прокрутке */
}
@media (max-width: 768px) {
  body {
    background-image:url({% static "deps/images/background.jpg" %});
  }
}
</style>
<body>
    <header>
        {% block header %}
        <nav>
            <div class="logo"><a href="{% url 'main:index' %}">FreshStyle</a></div>
          <ul class="nav-links">
            <li class="dropdown">
              <a>Аккаунт</a>
              <div class="dropdown-content">
                <a href="{% url 'users:login' %}">Войти</a>
                <a href="{% url 'users:registration' %}">Регистрация</a>
              </div>
            </li>
            <li><a href="{% url 'goods:category' %}">Товары</a></li>
            <li><a href="{% url 'main:index' %}">Главная</a></li>
          </ul>
        </nav>
        {% endblock %}
      </header>
    <div class="sidenav">
        {% block sidenav%}

        {% endblock %}
    </div>
    <main>
        {% block main %}

        {% endblock %}
    </main>
      <footer style="background-color: transparent; color: white; text-align: center; padding: 5px;">
        <p>All rights reserved.</br>&copy; 2024</p>
      </footer>
</body>
</html>

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/registration.css" %}">
{% endblock %}

{% block main %}
        <form>
          <h2>Вход</h2>
          <p>Еще нет аккаунта? <a href="{% url 'users:registration' %}">Создайте</a></p>
          <div>
            <input type="email" id="email" name="email" placeholder="Email" required>
          </div>
          <div>
            <input type="password" id="password" name="password" placeholder="Пароль" required>
          </div>
          <br>
          <input type="submit" value="Войти">
        </form>
{% endblock %}

users/templates/users/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Sakura - утилита ВКонтакте для автоматизации действий.">
    <meta name="author" content="Inovatik">


	  <meta property="og:site_name" content="FreshStyle" />
	  <meta property="og:site" content="sakuraduty.ru" />
	  <meta property="og:title" content="Shop"/>
	  <meta property="og:description" content="Молодежная одежда по цене шаурмы :)" />
	  <meta property="og:image" content="" />
	  <meta property="og:url" content="https://vk.com/FreshStyleShop" />
    <meta property="og:type" content="article" />

    <link rel="stylesheet" href=" {% static "deps/css/index.css" %} ">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Balega&display=swap">
    <link rel="stylesheet" href="{% static "deps/css/basket.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Balega&display=swap">
    <link rel="stylesheet" href=" {% static "deps/images/background.jpg" %} ">
    <script src="{% static "deps/js/index.js" %}" defer></script>
    <script src="{% static "deps/js/carousel.js" %}" defer></script>
    <script src="/js/index.js" defer></script>
    <script src="/js/carousel.js" defer></script>

    <title>{{ title }}</title>
</head>
<style>
body {
  background-image: url({% static "deps/images/background.jpg" %});
  background-size: cover; /* Растягивание изображения на весь фон */
  background-position: center; /* Центрируем изображение */
  background-attachment: fixed; /* Фиксируем изображение, чтобы оно оставалось на месте при прокрутке */
}
@media (max-width: 768px) {
  body {
    background-image:url({% static "deps/images/background.jpg" %});
  }
}
</style>
<body>
    <header>
       <nav>
            <div class="logo"><a href="{% url 'index' %}">FreshStyle</a></div>
          <ul class="nav-links">
            <li class="dropdown">
              <a>Аккаунт</a>
              <div class="dropdown-content">
                <a href="#">Корзина</a>
                <a href="#">Настройки</a>
                <a href="#">Выйти</a>
              </div>
            </li>
            <li><a href="/goods.html">Товары</a></li>
          </ul>
        </nav>
      </header>
    <main>
    </main>
      <footer style="background-color: transparent; color: white; text-align: center; padding: 5px;">
        <p>All rights reserved.</br>&copy; 2024</p>
      </footer>
</body>
</html>

users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/registration.css"%}">
{% endblock %}



{% block header %}
        <nav>
            <div class="logo"><a href="{% url 'main:index' %}">FreshStyle</a></div>
          <ul class="nav-links">
            <li><a href="{% url 'main:index' %}">Главная</a></li>
            <li><a href="{% url 'goods:category' %}">Товары</a></li>
          </ul>
        </nav>
{% endblock %}

{% block main %}
        <form>
            <h2>Регистрация</h2>
            <p>Уже есть аккаунт? <a href="{% url 'users:login' %}">Войдите</a></p>
            <div>
                <input type="name" id="name" name="name" placeholder="Имя" required>
              </div>
            <div>
              <input type="email" id="email" name="email" placeholder="Email" required>
            </div>
            <div>
              <input type="tel" id="phone" name="phone" placeholder="Телефон" required>
            </div>
            <div>
              <input type="password" id="password" name="password" placeholder="Пароль" required>
            </div>
            <br>
            <input type="submit" value="Зарегистрироваться">
          </form>
{% endblock %}